---
- name: Extração de dados
  hosts: Servers
  roles:
    - Recursos      

- name: Envio de Email
  hosts: localhost
  tasks:
    - name: Enviando relatórios por E-mail...
      ansible.builtin.script: /joaokienen/SHELL/MAIL/SendEmail.sh
...
