---

- name: Colentando dados!  
  set_fact:
    my_pass: "{{ pass_alias }}"
- debug:
        msg: "{{ ansible_hostname }} = ' {{ my_pass }} '"

- name: Alterando Senha!
  user:
    name: root
    update_password: always
    password: "{{ my_pass|password_hash('sha512') }}"

... 
